# Generated by Django 4.1.2 on 2022-11-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.DurationField(verbose_name='Дата начала стажа'),
        ),
    ]
