# Generated by Django 4.1.2 on 2022-11-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0002_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.DateField(verbose_name='Дата начала стажа'),
        ),
    ]
