# Generated by Django 4.1.5 on 2023-03-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0004_alter_doctor_options_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/', verbose_name='Фото')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default=1, max_length=90, verbose_name='Специализация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor-photo/', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
