# Generated by Django 4.1.5 on 2023-03-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0005_photo_alter_doctor_options_remove_doctor_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
