# Generated by Django 4.1.5 on 2023-03-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0006_alter_services_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название фото'),
        ),
    ]
